apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: ingress-patch.yml
  target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: heimdal
    namespace: heimdal
- path: deployment-patch.yml
  target:
    group: apps/v1
    version: v1
    kind: Deployment
    name: heimdal
    namespace: heimdal
