apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: heimdal
  annotations:
    kubernetes.io/ingress.class: nginx  
    cert-manager.io/issuer: letsencrypt-prod
    cert-manager.io/issuer-kind: ClusterIssuer
  namespace: heimdal
spec:
  rules:
    - host: heimdal.local.wep4you.com
      http:
        paths:
          - backend:
              service:
                name: heimdal
                port:
                  number: 80
            pathType: ImplementationSpecific
            path: ''
  tls:
    - hosts:
        - heimdal.local.wep4you.com
      secretName: tls-heimdal-ingress
