kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: heimdal-pvc
  namespace: heimdal
  labels:
    app: heimdal
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
